import { useEffect, useState } from 'react';
import { t, locale } from './i18n';
import type { AcceptanceItem, FieldIntent, Overview, PriorExperience, Run, RunExperience } from './types';
import { ExperiencePanel } from './ExperiencePanel';

type Props = {
  overview: Overview | null; runs: Run[];
  onModes: () => void; onManualGrid: () => void; onExperiments: () => void; onAnomaly: () => void;
  onRun: (id: string) => void; onReport: (id: string) => void;
  onEvidence: (item: AcceptanceItem) => void;
  onDesignWithHistory: (prior: PriorExperience) => void;
  fieldIntentDraft: FieldIntent; onFieldIntentDraftChange: (intent: FieldIntent) => void;
  onDesignWithFieldIntent: (intent: FieldIntent) => void; onClearFieldIntent: () => void;
};
const activeStates = new Set(['queued', 'running', 'stop_requested']);
const runStates = (): Record<string, string> => ({ queued: t("Queued", "Kuyrukta"), running: t("Running", "Çalışıyor"), stop_requested: t("Waiting for stop", "Durdurma bekleniyor"), completed: t("Completed", "Tamamlandı"), stopped: t("Stopped", "Durduruldu"), failed: t("Failed", "Başarısız"), cancelled: t("Cancelled", "İptal edildi") });
const purposes = (): Record<string, string> => ({ research: t("Research", "Araştırma"), baseline: t("CPU baseline", "CPU başlangıç ölçümü"), 'mode-grid': t("Method comparison", "Yöntem karşılaştırması"), 'mode-stream': t("CPU OMR diagnostic · not scored", "CPU OMR tanısı · puanlanmaz") });
const time = (value?: string) => value ? new Date(value).toLocaleString(locale(), { dateStyle: 'medium', timeStyle: 'short' }) : t("No timestamp recorded", "Zaman kaydı yok");
const freshRun = (run: Run) => !run.stale && !run.unavailable;
function observedCapacity(system?: Overview['system']) {
  const ram = system?.memory.total_bytes;
  const vram = system?.gpu.total_mib;
  return {
    ram_gib: ram != null && Number.isFinite(ram) && ram > 0 ? ram / 1024 ** 3 : null,
    vram_gib: vram != null && Number.isFinite(vram) && vram > 0 ? vram / 1024 : null,
    logical_cpu_count: system?.cpu.logical_count ?? null,
  };
}

export function AgentWorkspace({ overview, runs, onModes, onManualGrid, onExperiments, onRun, onReport, onEvidence, onAnomaly, onDesignWithHistory, fieldIntentDraft, onFieldIntentDraftChange, onDesignWithFieldIntent, onClearFieldIntent }: Props) {
  const [experience, setExperience] = useState<RunExperience | null>(null);
  const connected = !!overview?.lab.connected;
  const currentExperience = connected && experience && runs.some(run => freshRun(run) && ['completed', 'stopped', 'failed'].includes(run.state) && run.run_id === experience.run_id && run.report_sha256 === experience.report_sha256) ? experience : null;
  const capacity = observedCapacity(overview?.system);
  const modelEnabled = connected && !!overview?.lab.model_runs_enabled;
  const active = runs.filter(run => freshRun(run) && activeStates.has(run.state));
  const latest = [...runs].sort((a, b) => Date.parse(b.updated_at ?? b.created_at ?? '') - Date.parse(a.updated_at ?? a.created_at ?? ''));
  const reports = runs.filter(run => freshRun(run) && run.report_sha256);
  const anomaly = connected && !!overview?.lab.suites.some(suite => suite.track === 'anomaly');
  const progress = overview?.development_progress;
  const evidence = (id: string) => overview?.acceptance.items.find(item => item.id === id);
  const modelEvidence = evidence('M0.13');
  const connectionReason = overview?.lab.reason?.includes('Lab API is not configured') ? t("Lab API is not configured yet.", "Lab API henüz yapılandırılmadı.") : overview?.lab.reason;
  const next = !connected ? t("Verify the Lab connection and inspect existing records and evidence.", "Lab bağlantısını doğrula; mevcut kayıt ve kanıtları incele.") : active.length ? t("Monitor the active run and wait until its final report is verified.", "Aktif işi izle; terminal rapor doğrulanana kadar sonucu bekle.") : modelEnabled ? t("Choose the goal and data; let the local agent design experiments, the backend measure results, and those results inform the next proposal.", "Hedef ve veriyi seç; yerel eylemci deneyleri tasarlasın, backend sonuçlarını ölçsün ve sonraki öneriye taşısın.") : t("Explore the local agent workflow. Model calls are disabled in this profile; manual CPU comparison is available separately.", "Yerel eylemci akışını incele. Bu profilde model çağrıları kapalı; manuel CPU karşılaştırması ayrı seçilebilir.");
  const capabilities = [
    { name: t("Data selection and quality", "Veri seçimi ve kalite"), description: t("Authorized PostgreSQL source, asset and UTC range, or a synthetic snapshot. The database source requires separate configuration.", "Yetkili PostgreSQL kaynağı, varlık ve UTC aralığı veya sentetik snapshot. DB kaynağı ayrıca yapılandırılır."), state: connected ? t("Data workflow available", "Veri yolu açık") : t("Connection required", "Bağlantı gerekli"), ready: connected, label: t("Select data", "Veri seç"), action: onModes },
    { name: t("Statistics and sensor relationships", "İstatistik ve sensör ilişkileri"), description: t("Distributions, missing values, correlation and autocorrelation. Descriptive analysis for unlabeled data.", "Dağılım, eksikler, korelasyon ve otokorelasyon. Etiketsiz veri için tanımlayıcı analiz."), state: connected ? t("CPU analysis available", "CPU analizi açık") : t("Connection required", "Bağlantı gerekli"), ready: connected, label: t("Open analysis", "Analizi aç"), action: onModes },
    { name: t("LSH / OPTICS / SOM", "LSH / OPTICS / SOM"), description: t("Operating mode learning, method hyperparameters and controlled comparison. The algorithms are available.", "Çalışma modu öğrenme, yöntem hiperparametreleri ve kontrollü karşılaştırma. Algoritmalar mevcut."), state: connected ? t("CPU experiment workflow available", "CPU deney yolu açık") : t("Connection required", "Bağlantı gerekli"), ready: connected, label: t("Compare methods", "Yöntemleri karşılaştır"), action: onManualGrid },
    { name: t("NN, residuals and OMR", "NN, residual ve OMR"), description: t("Mode tolerance → normal value estimate → sensor residuals and OMR. Mode/SOM distances remain separate; the long diagnostic stream is not scored.", "Mod toleransı → normal değer tahmini → sensör residual ve OMR. Mod/SOM uzaklıkları ayrı kalır; uzun tanı akışı puanlanmaz."), state: connected ? t("CPU stream workflow available", "CPU akış yolu açık") : t("Connection required", "Bağlantı gerekli"), ready: connected, label: t("Open OMR stream", "OMR akışını aç"), action: onModes },
    { name: t("Anomaly comparison", "Anomali karşılaştırması"), description: t("Independent Scorer and Referee on a registered suite. False alarms and early detection require suitable labels.", "Kayıtlı süit üzerinde bağımsız Scorer ve Referee. Yanlış alarm ve erken yakalama için uygun etiket gerekir."), state: anomaly ? t("Registered suite available", "Kayıtlı süit var") : connected ? t("Suite required", "Süit gerekli") : t("Connection required", "Bağlantı gerekli"), ready: anomaly, label: t("Select experiment", "Deney seç"), action: onAnomaly },
    { name: t("Main local experiment agent", "Ana yerel deney eylemcisi"), description: t("Local Qwen proposes methods and hyperparameters; the backend executes them and independent results inform the next proposal. A finite budget and resource admission are required.", "Yerel Qwen yöntem ve hiperparametre önerir; backend yürütür, bağımsız sonuçlar sonraki öneriye döner. Sonlu bütçe ve kaynak kabulü gerekir."), state: modelEnabled ? t("Model workflow available", "Model yolu açık") : t("Model calls disabled", "Model çağrıları kapalı"), ready: connected, label: t("Configure local agent", "Yerel eylemciyi yapılandır"), action: onModes },
  ];
  return <div className="agent-workspace page-stack" data-testid="agent-workspace">
    <nav className="agent-section-links" aria-label={t("Agent sections", "Eylemci bölümleri")}><a href="#agent-status">{t("Status", "Durum")}</a><a href="#agent-field-intent">{t("Field intent", "Saha amacı")}</a><a href="#agent-topology">{t("System workflow", "Sistem akışı")}</a><a href="#agent-capabilities">{t("Capabilities", "Yetenekler")}</a><a href="#agent-experience">{t("Experiment memory", "Deney hafızası")}</a><a href="#teacher-draft">{t("Optional teacher", "İsteğe bağlı öğretmen")}</a></nav>
    <section className="panel agent-status" id="agent-status" aria-labelledby="agent-status-title">
      <div className="panel-heading"><div><h2 id="agent-status-title">{t("Local experiment agent", "Yerel deney eylemcisi")}</h2><p>{t("The local model designs the experiment; the backend executes it and results inform the next proposal", "Deneyi yerel model tasarlar; backend yürütür, sonuçlar sonraki öneriye döner")}</p></div><span className={`agent-label ${connected ? 'available' : 'waiting'}`}>{connected ? t("Lab connected", "Lab bağlı") : t("Lab disconnected", "Lab bağlı değil")}</span></div>
      <div className="agent-status-body"><div>
        <h3>{!overview ? t("Waiting for live status", "Canlı durum bekleniyor") : !connected ? t("Connect to start experiments", "Deney başlatmak için bağlantı gerekiyor") : active.length ? t(`Monitoring ${active.length} active runs`, `${active.length} aktif iş izleniyor`) : t("No active runs", "Aktif iş yok")}</h3>
        <p>{!overview ? t("Run status and resource availability cannot be verified before the API responds.", "API yanıtı gelmeden çalışma durumu veya kaynak uygunluğu doğrulanamaz.") : !connected ? connectionReason || t("The Lab API connection has not been configured in this installation.", "Bu kurulumda Lab API bağlantısı kurulmadı.") : modelEnabled ? t("CPU experiments and the local model workflow are available. Each new run must pass server budget and resource admission.", "CPU deneyleri ve yerel model yolu açık. Yeni koşu sunucunun bütçe ve kaynak kabulünden geçer.") : t("The CPU workflow is available in this profile, but main local model calls are disabled. The local agent cannot start; a manual zero-token grid is available separately.", "Bu profilde CPU yolu açık, ana yerel model çağrıları kapalı. Yerel eylemci başlatılamaz; manuel sıfır token grid ayrı seçilebilir.")}</p>
        {active.slice(0, 2).map(run => <button className="agent-active-run" key={run.run_id} onClick={() => onRun(run.run_id)}><span>{runStates()[run.state] ?? run.state} · {purposes()[run.purpose ?? ''] ?? t("Run", "Koşu")}</span><code>{run.run_id}</code><span>{t("Monitor / stop", "İzle / durdur")}</span></button>)}
        {runs.some(run => !freshRun(run)) && <p className="agent-note">{t("Some tracked records could not be refreshed and were excluded from the active run count.", "Bazı izlenen kayıtlar güncel okunamadı; aktif iş sayısına dahil edilmedi.")}</p>}
      </div><div className="agent-next"><strong>{t("Next action", "Sıradaki eylem")}</strong><p>{next}</p><div className="agent-actions"><button className="button primary" onClick={active.length || !connected ? onExperiments : onModes}>{active.length || !connected ? t("Inspect runs", "Koşuları incele") : t("Design an experiment with the local agent", "Yerel eylemciyle deney tasarla")}</button><button className="button secondary" onClick={onManualGrid} disabled={!connected}>{t("Manual CPU comparison · 0 tokens", "Manuel CPU karşılaştırması · 0 token")}</button><button className="button secondary" onClick={onExperiments}>{t("History and reports", "Geçmiş ve raporlar")}</button></div></div></div>
      <div className="agent-connection"><span>{t("Local model: ", "Yerel model: ")}<strong>{modelEnabled ? t("Calls enabled", "Çağrı yolu açık") : t("Disabled", "Kapalı")}</strong></span><span>{t("AOS coexistence: ", "AOS birlikte çalışma: ")}<strong>{evidence('M0.AOS.7')?.status === 'passed' ? t("Recorded acceptance passed", "Kayıtlı kabul geçti") : t("Not verified yet", "Henüz doğrulanmadı")}</strong></span><span>{t("Data timestamp: ", "Veri zamanı: ")}<strong>{overview ? time(overview.generated_at) : t("Waiting", "Bekleniyor")}</strong></span></div>
      <p className="agent-note">{t("Observed host: RAM ", "Gözlenen host: RAM ")}{capacity.ram_gib === null ? t("unknown", "bilinmiyor") : `${capacity.ram_gib.toFixed(1)} GiB`}{t(", VRAM ", ", VRAM ")}{capacity.vram_gib === null ? t("unknown", "bilinmiyor") : `${capacity.vram_gib.toFixed(1)} GiB`}{t(", logical CPUs ", ", mantıksal CPU ")}{capacity.logical_cpu_count ?? t("unknown", "bilinmiyor")}{t(". Total CPU/RAM/disk admission shared with AOS and a single GPU queue require bounded model calls, reserves and resource handoff. Total capacity is not free capacity or a training allocation.", ". AOS ile toplam CPU/RAM/disk kabulü ve tek GPU sırası; sınırlı model çağrıları, rezerv ve kaynak devri gerekir. Toplam kapasite, boş kaynak veya eğitim tahsisi değildir.")}</p>
    </section>

    <AgentTopology connected={connected} modelEnabled={modelEnabled}/>
    <FieldIntentForm value={fieldIntentDraft} connected={connected} onChange={onFieldIntentDraftChange} onDesign={onDesignWithFieldIntent} onClear={onClearFieldIntent}/>
    <section className="panel" id="agent-capabilities" aria-labelledby="agent-capabilities-title"><div className="panel-heading"><div><h2 id="agent-capabilities-title">{t("General capabilities", "Genel yetenekler")}</h2><p>{t("Algorithm availability and the workflow available in this installation are shown separately.", "Algoritmanın mevcut olması ve bu kurulumdaki çalışma yolu ayrı gösterilir.")}</p></div>{modelEvidence && <button className="button secondary small" onClick={() => onEvidence(modelEvidence)}>{t("Model evidence", "Model kanıtı")}</button>}</div>
      <div className="agent-capabilities">{capabilities.map(item => <div className="agent-capability" key={item.name}><div><h3>{item.name}</h3><p>{item.description}</p></div><span className={`agent-label ${item.ready ? 'available' : 'waiting'}`}>{item.state}</span><button className="button secondary small" onClick={item.action} disabled={!item.ready}>{item.label}</button></div>)}
        <div className="agent-capability"><div><h3>{t("Optional teacher support", "İsteğe bağlı öğretmen desteği")}</h3><p>{t("Draft support from a larger model for experiment ideas, model improvement or architecture review. Local or explicitly approved external API; the call/training backend is not available yet.", "Daha büyük modelden deney fikri, model geliştirme veya mimari değerlendirme için taslak. Yerel ya da açık onaylı dış API; çağrı/eğitim backend'i henüz yok.")}</p></div><span className="agent-label waiting">{t("Draft preparation", "Taslak hazırlama")}</span><a className="button secondary small" href="#teacher-draft">{t("Prepare draft", "Taslağı hazırla")}</a></div>
        <div className="agent-capability"><div><h3>{t("Skills and continuous improvement", "Skill ve sürekli gelişim")}</h3><p>{t("Verified development findings can be explicitly selected for a new experiment context. There is no automatic history scan. Skill publication and automatic model releases require independent evaluation, holdout and rollback.", "Doğrulanmış geliştirme bulguları açık seçimle yeni deney bağlamına taşınabilir. Otomatik geçmiş taraması yok. Skill yayını ve otomatik yeni model sürümü için bağımsız değerlendirme, holdout ve rollback gerekir.")}</p></div><span className="agent-label waiting">{t("Improvement pipeline incomplete", "Gelişim zinciri kısmi")}</span><a className="button secondary small" href="#agent-experience">{t("Inspect memory", "Hafızayı incele")}</a></div>
      </div>
    </section>

    <section className="panel" id="agent-learning" aria-labelledby="agent-learning-title"><div className="panel-heading"><div><h2 id="agent-learning-title">{t("Experiment and improvement history", "Deney ve gelişim geçmişi")}</h2><p>{t("Only actual connected run records. Completing a run does not demonstrate agent improvement.", "Yalnız bağlı gerçek koşu kayıtları. Bir koşunun bitmesi, eylemcinin iyileştiğini göstermez.")}</p></div><button className="button secondary small" onClick={onExperiments}>{t("All runs", "Tüm koşular")}</button></div>
      <ol className="agent-learning-path"><li><strong>{t("Experiment record", "Deney kaydı")}</strong><span>{runs.length} {t(" tracked records", " izlenen kayıt")}</span></li><li><strong>{t("Independent report", "Bağımsız rapor")}</strong><span>{reports.length} {t(" current report references", " güncel rapor referansı")}</span></li><li><strong>{t("Holdout / comparison", "Holdout / karşılaştırma")}</strong><span>{t("Each decision needs evidence", "Her kararın kanıtı gerekir")}</span></li><li><strong>{t("Skill / new model", "Skill / yeni model")}</strong><span>{t("Automatic promotion not ready", "Otomatik terfi hazır değil")}</span></li></ol>
      <p className="agent-note">{t("KEEP is a selection on the development set. Lasting improvement requires independent validation, suitable training records and comparison with a new version. DISCARD and failed experiments are also retained as records.", "KEEP, geliştirme kümesinde seçimdir. Kalıcı gelişim; bağımsız doğrulama, uygun eğitim kaydı ve yeni sürüm karşılaştırmasıyla gösterilir. DISCARD veya başarısız deney de kayıt olarak korunur.")}</p>
      {latest.length ? <div className="agent-history">{latest.slice(0, 5).map(run => <div className="agent-history-row" key={run.run_id}><div><button className="uuid-button" onClick={() => onRun(run.run_id)}>{run.run_id}</button><span>{purposes()[run.purpose ?? ''] ?? t("No run type recorded", "Tür kaydı yok")} · {time(run.updated_at ?? run.created_at)}</span></div><span className={`agent-label ${freshRun(run) && run.state === 'completed' ? 'available' : 'waiting'}`}>{!freshRun(run) ? t("Could not refresh", "Güncel okunamadı") : runStates()[run.state] ?? run.state}</span><div><span className="agent-history-outcome">{run.purpose === 'mode-stream' ? t("Diagnostic stream; no improvement score", "Tanı akışı; gelişim puanı yok") : t("Assess improvement from the report", "Gelişim sonucu rapordan değerlendirilir")}</span><button className="button secondary small" onClick={() => onReport(run.run_id)} disabled={!freshRun(run) || !run.report_sha256}>{t("Open report", "Raporu aç")}</button></div></div>)}</div> : <div className="empty-state"><strong>{t("No connected run records yet", "Henüz bağlı koşu kaydı yok")}</strong><span>{t("Track a registered run from the Experiments screen or start with the data/method workflow. History is not populated with sample records.", "Deneyler ekranından kayıtlı bir koşuyu izlemeye ekleyin veya veri/yöntem akışından başlayın. Geçmiş örnek kayıtlarla doldurulmaz.")}</span></div>}
      {progress && <div className="agent-development"><strong>{t("Development record · ", "Geliştirme kaydı · ")}{time(progress.updated_at)}</strong><p>{progress.latest_result}</p><details><summary>{t("Open deliverables", "Açık teslimler")}</summary><p>{progress.next_step}</p></details></div>}
    </section>

    <ExperiencePanel runs={runs} connected={connected} onVerifiedChange={setExperience} onReport={onReport} onDesign={onDesignWithHistory}/>
    <TeacherDraft runs={reports.filter(run => run.state === 'completed' && run.purpose !== 'mode-stream')} experience={currentExperience} system={overview?.system} observedAt={overview?.generated_at} trainingEvidence={evidence('M0.14')} onEvidence={onEvidence}/>
  </div>;
}

function AgentTopology({ connected, modelEnabled }: { connected: boolean; modelEnabled: boolean }) {
  const steps = [
    [t("Goal and authorized data", "Hedef ve yetkili veri"), t("Asset declaration, snapshot and time/token budget.", "Varlık beyanı, snapshot ve süre/token bütçesi.")],
    [t("LOCAL experiment planner", "YEREL deney planlayıcı"), t("The main local model proposes methods and hyperparameters.", "Ana yerel model yöntem ve hiperparametre önerir.")],
    [t("Director and resource queue", "Director ve kaynak sırası"), t("Proposal validation, budget, CPU/RAM and model call admission.", "Öneri doğrulaması, bütçe, CPU/RAM ve model çağrısı kabulü.")],
    [t("CPU sandbox and methods", "CPU sandbox ve yöntemler"), t("The backend executes an LSH / OPTICS / SOM candidate within limits.", "Backend LSH / OPTICS / SOM adayını sınırlar içinde yürütür.")],
    [t("Independent Scorer / Referee", "Bağımsız Scorer / Referee"), t("Development scores, guards and decision summaries are verified.", "Geliştirme skorları, guard ve karar özeti doğrulanır.")],
    [t("Report and selected memory", "Rapor ve seçili hafıza"), t("Report bound by hash; only explicitly selected findings from history.", "Hash ile bağlı rapor; geçmişten yalnız açıkça seçilen bulgular.")],
    [t("Next LOCAL proposal", "Sonraki YEREL öneri"), t("The verified result summary returns to the model through the Director.", "Doğrulanmış sonuç özeti Director üzerinden modele geri döner.")],
  ];
  return <section className="panel agent-topology" id="agent-topology" aria-labelledby="agent-topology-title">
    <div className="panel-heading"><div><h2 id="agent-topology-title">{t("How does the system work?", "Sistem nasıl çalışır?")}</h2><p>{t("The main researcher is the local model; teacher support is optional.", "Ana araştırmacı yerel modeldir; öğretmen desteği isteğe bağlıdır.")}</p></div><span className={`agent-label ${modelEnabled ? 'available' : 'waiting'}`}>{modelEnabled ? t("Local model workflow available", "Yerel model yolu açık") : t("Local model workflow disabled", "Yerel model yolu kapalı")}</span></div>
    <ol className="agent-topology-flow">{steps.map(([title, description], index) => <li key={title}><span className="agent-topology-index" aria-hidden="true">{index + 1}</span><strong>{title}</strong><p>{description}</p>{index < steps.length - 1 && <span className="agent-topology-arrow" aria-hidden="true">→</span>}</li>)}</ol>
    <p className="agent-note">{t("Result-driven iteration carries up to 30 recent feedback summaries from the same run into the next model context. Verified DEV result summaries may be used; hidden labels, raw sensor series and holdout are withheld from the model. This adapts context; it does not train model weights or automatically promote a model.", "Sonuçlarla yineleme, aynı koşuda en fazla 30 son geri bildirim özetini sonraki model bağlamına taşır. Doğrulanmış DEV sonuç özetleri kullanılabilir; gizli etiketler, ham sensör serisi ve holdout modele verilmez. Bu bağlam uyarlamasıdır; model ağırlığı eğitimi veya otomatik terfi değildir.")}</p>
    <div className="agent-topology-branches">
      <div><h3>{t("Optional teacher", "İsteğe bağlı öğretmen")}</h3><span className="agent-label waiting">{t("Draft only · no backend", "Yalnız taslak · backend yok")}</span><p>{t("Experiment ideas, model improvement and architecture review. Local or external API; each external API request requires explicit approval. Suggestions are verified separately; the teacher is not a prerequisite for the main workflow.", "Deney fikirleri, model geliştirme ve mimari değerlendirme. Yerel veya dış API; dış API'de her istek için açık onay gerekir. Öneriler ayrıca doğrulanır; öğretmen ana akışın önkoşulu değildir.")}</p></div>
      <div><h3>{t("AOS control API", "AOS kontrol API'si")}</h3><span className={`agent-label ${connected ? 'available' : 'waiting'}`}>{connected ? t("Lab API connected", "Lab API bağlı") : t("Lab connection required", "Lab bağlantısı gerekli")}</span><p>{t("AOS calls the start/monitor/stop/report workflow with a separate owner and budget. Actual web field mappings require separate acceptance.", "AOS başlat/izle/durdur/rapor akışını ayrı owner ve bütçe ile çağırır. Gerçek web alan eşlemelerinin kabulü ayrıca gerekir.")}</p></div>
      <div><h3>{t("Single shared GPU arbiter", "Tek ortak GPU arbiter")}</h3><span className="agent-label waiting">{t("Shared GPU acceptance pending", "Ortak GPU kabulü açık")}</span><p>{t("AOS and local model calls use a single shared queue, finite turns and resource handoff rules. This CPU profile grants no model/GPU authority; this screen does not verify concurrent GPU acceptance.", "AOS ve yerel model çağrıları tek paylaşımlı sıraya, sonlu turn ve kaynak devri kurallarına tabidir. Bu CPU profili model/GPU yetkisi açmaz; eşzamanlı GPU kabulü bu ekranla doğrulanmaz.")}</p></div>
    </div>
  </section>;
}

function FieldIntentForm({ value, connected, onChange, onDesign, onClear }: { value: FieldIntent; connected: boolean; onChange: (intent: FieldIntent) => void; onDesign: (intent: FieldIntent) => void; onClear: () => void }) {
  const intent = { ...value, asset_id: value.asset_id.trim(), objective: value.objective.trim() };
  const assetLength = Array.from(intent.asset_id).length, objectiveLength = Array.from(intent.objective).length;
  const controls = /[\u0000-\u001f\u007f]/.test(intent.asset_id + intent.objective);
  const valid = assetLength >= 1 && assetLength <= 128 && objectiveLength >= 1 && objectiveLength <= 600 && !controls;
  return <section className="panel" id="agent-field-intent" aria-labelledby="field-intent-title"><div className="panel-heading"><div><h2 id="field-intent-title">{t("Field research intent", "Saha araştırma amacı")}</h2><p>{t("Enter the asset label and objective; choose data, methods and budget in the next step.", "Varlık etiketini ve hedefi yazın; veri, yöntem ve bütçeyi sonraki adımda seçin.")}</p></div><span className="agent-label waiting">{t("User declaration", "Kullanıcı beyanı")}</span></div>
    <form className="run-form" onSubmit={event => { event.preventDefault(); if (connected && valid) onDesign(intent); }}>
      <label>{t("Asset label", "Varlık etiketi")}<input value={value.asset_id} maxLength={256} onChange={event => onChange({ ...value, asset_id: event.target.value })} placeholder={t("E.g. pump-01", "Örn. pompa-01")}/><span>{t(`${assetLength}/128 characters`, `${assetLength}/128 karakter`)}</span></label>
      <label>{t("Research goal", "Araştırma amacı")}<select value={value.goal_kind} onChange={event => onChange({ ...value, goal_kind: event.target.value as FieldIntent['goal_kind'] })}><option value="digital_twin">{t("Digital twin research", "Dijital ikiz araştırması")}</option><option value="predictive_maintenance">{t("Predictive maintenance research", "Kestirimci bakım araştırması")}</option></select></label>
      <label>{t("Working objective", "Çalışma hedefi")}<input value={value.objective} maxLength={1200} onChange={event => onChange({ ...value, objective: event.target.value })} placeholder={t("E.g. compare normal operating modes under load changes", "Örn. yük değişimlerinde normal çalışma modlarını karşılaştır")}/><span>{t(`${objectiveLength}/600 characters`, `${objectiveLength}/600 karakter`)}</span></label>
      {(controls || assetLength > 128 || objectiveLength > 600) && <p role="alert" className="field-error">{t("The asset label may contain up to 128 characters and the objective up to 600; control characters are not allowed.", "Varlık en fazla 128, hedef en fazla 600 karakter olabilir; kontrol karakterleri kullanılamaz.")}</p>}
      <div className="agent-actions"><button className="button primary" type="submit" disabled={!connected || !valid}>{t("Design a local experiment for this intent", "Bu amaçla yerel deney tasarla")}</button><button className="button secondary" type="button" onClick={onClear} disabled={!value.asset_id && !value.objective}>{t("Clear intent", "Amacı temizle")}</button></div>
    </form><p className="agent-note">{t("The asset label is your declaration; it is not evidence of an authorized source/asset mapping or maintenance action. The objective does not automatically change methods, scores or budgets. Submitting a draft does not establish that it was used; context evidence is checked separately at the end of the run.", "Varlık etiketi sizin beyanınızdır; yetkili kaynak/varlık eşlemesi veya bakım aksiyonu kanıtı değildir. Hedef yöntem, skor ve bütçeyi otomatik değiştirmez. Taslağın gönderilmesi kullanıldığı anlamına gelmez; koşu sonunda bağlam kanıtı ayrıca okunur.")}</p>
  </section>;
}

function TeacherDraft({ runs, experience, system, observedAt, trainingEvidence, onEvidence }: { runs: Run[]; experience: RunExperience | null; system?: Overview['system']; observedAt?: string; trainingEvidence?: AcceptanceItem; onEvidence: (item: AcceptanceItem) => void }) {
  const [teacher, setTeacher] = useState('Qwen/Qwen3.5-9B');
  const [teacherProvider, setTeacherProvider] = useState<'local' | 'external_api'>('local');
  const [student, setStudent] = useState('Local research agent');
  const [purpose, setPurpose] = useState('experiment_ideas');
  const [objective, setObjective] = useState('Improve operating mode and anomaly research');
  const [dataset, setDataset] = useState('');
  const [runId, setRunId] = useState('');
  const [seconds, setSeconds] = useState(1800);
  const [tokens, setTokens] = useState(30000);
  const [ram, setRam] = useState(8);
  const [vram, setVram] = useState(12);
  const [draft, setDraft] = useState<string | null>(null);
  const [error, setError] = useState<'required' | 'reference' | 'budget' | null>(null);
  const currentRun = runs.find(run => run.run_id === runId);
  const capacity = observedCapacity(system);
  const ramMax = capacity.ram_gib === null ? undefined : Math.floor(capacity.ram_gib);
  const vramMax = capacity.vram_gib === null ? undefined : Math.floor(capacity.vram_gib);
  useEffect(() => {
    if (ramMax != null && ramMax >= 1) setRam(value => Math.min(value, ramMax));
    if (vramMax != null && vramMax >= 1) setVram(value => Math.min(value, vramMax));
    setDraft(null);
  }, [ramMax, vramMax]);
  useEffect(() => {
    setDraft(null);
    if (experience) setRunId(runs.some(run => run.run_id === experience.run_id) ? experience.run_id : '');
  }, [experience?.run_id, experience?.report_sha256]);
  function exportDraft(event: React.FormEvent) {
    event.preventDefault(); setError(null); setDraft(null);
    const preparation = ['teacher_examples', 'sft_data', 'lora_evaluation', 'qlora_evaluation'].includes(purpose);
    if (!teacher.trim() || !student.trim() || !objective.trim() || (preparation && !dataset.trim() && !currentRun && !experience)) { setError('required'); return; }
    if (/^[a-z][a-z0-9+.-]*:\/\//i.test(teacher.trim())) { setError('reference'); return; }
    if (!Number.isInteger(seconds) || seconds < 1 || seconds > 14400 || !Number.isInteger(tokens) || tokens < 1 || tokens > 350000 || !Number.isInteger(ram) || ram < 1 || (ramMax != null && ram > ramMax) || !Number.isInteger(vram) || vram < 1 || (vramMax != null && vram > vramMax)) { setError('budget'); return; }
    const payload = {
      schema: 'agent-teaching-draft.v2', status: 'draft', created_at: new Date().toISOString(), training_started: false,
      teacher: { model_reference: teacher.trim(), runtime: teacherProvider, profile_verified: false, approved: false, executed: false, needs_explicit_approval: teacherProvider === 'external_api', approval_scope: teacherProvider === 'external_api' ? 'per_request' : null },
      main_agent_runtime: 'local',
      student_reference: student.trim(), purpose, objective: objective.trim(),
      data: { reference: dataset.trim() || null, run_id: currentRun?.run_id ?? experience?.run_id ?? null, report_sha256: currentRun?.report_sha256 ?? experience?.report_sha256 ?? null, training_eligibility: 'unreviewed', usage_profile: 'noncommercial_research', raw_data_included: false, holdout_allowed: false },
      experience_preparation: experience ? { run_id: experience.run_id, report_sha256: experience.report_sha256, verification: experience.verification, eligible_training_records: 0, records: experience.records.map(record => ({ record_id: record.record_id, experiment_sha256: record.experiment_sha256 ?? null, trajectory_sha256: record.trajectory_sha256 ?? null, training_eligibility: record.training_eligibility })) } : null,
      budget: { wall_seconds: seconds, model_tokens: tokens, cpu_threads: 2, ram_gib: ram, vram_gib: vram },
      observed_capacity: { ...capacity, observed_at: observedAt ?? null },
      resource_policy: { shared_with_aos: true, admission_required: true, bounded_calls_and_yield_required: true, gpu_reserved: false },
      evaluation: { independent_comparison_required: true, holdout_required: true, rollback_required: true, auto_activate: false },
    };
    const value = JSON.stringify(payload, null, 2);
    const url = URL.createObjectURL(new Blob([value], { type: 'application/json' }));
    const link = document.createElement('a'); link.href = url; link.download = 'agent-teaching-draft.json'; link.click();
    window.setTimeout(() => URL.revokeObjectURL(url), 1000); setDraft(value);
  }
  return <details className="panel agent-teacher" id="teacher-draft"><summary>{t("Optional teacher support · draft preparation", "İsteğe bağlı öğretmen desteği · taslak hazırlığı")}</summary><div className="panel-heading"><div><h2 id="teacher-draft-title">{t("Teacher support and training preparation", "Öğretmen desteği ve eğitim hazırlığı")}</h2><p>{t("A larger model may offer optional support for experiment ideas, model improvement and architecture review. The main experiment agent remains local; this form only downloads a draft.", "Deney fikirleri, model geliştirme ve mimari değerlendirme için daha büyük bir model isteğe bağlı destek olabilir. Ana deney eylemcisi yerel kalır; bu form yalnız taslak indirir.")}</p></div><span className="agent-label waiting">{t("Training has not been run", "Eğitim henüz çalıştırılmadı")}</span></div>
    <form className="run-form agent-draft-form" onSubmit={exportDraft}>
      {experience && <p className="agent-note agent-draft-full">{t("Selected verified experiment memory: ", "Seçilen doğrulanmış deney hafızası: ")}{experience.run_id} · {experience.records.length} {t(" records. Preparation references are added to the draft; training eligibility has not been granted.", " kayıt. Hazırlık referansları taslağa eklenir; eğitim uygunluğu henüz verilmedi.")}</p>}
      <label>{t("Teacher provider", "Öğretmen sağlayıcısı")}<select value={teacherProvider} onChange={e => { setTeacherProvider(e.target.value as 'local' | 'external_api'); setDraft(null); }}><option value="local">{t("Local model (default)", "Yerel model (varsayılan)")}</option><option value="external_api">{t("External API · explicit approval for each request", "Dış API · her istek için açık onay")}</option></select></label>
      <label>{t("Teacher model / profile reference", "Öğretmen model / profil referansı")}<input required maxLength={160} value={teacher} onChange={e => { setTeacher(e.target.value); setDraft(null); }}/></label>
      <label>{t("Target agent / model", "Hedef eylemci / model")}<input required maxLength={160} value={student} onChange={e => { setStudent(e.target.value); setDraft(null); }}/></label>
      <label>{t("Support / preparation purpose", "Destek / hazırlık amacı")}<select value={purpose} onChange={e => { setPurpose(e.target.value); setDraft(null); }}><option value="experiment_ideas">{t("Experiment ideas", "Deney fikirleri")}</option><option value="model_improvement">{t("Model improvement suggestions", "Model geliştirme önerileri")}</option><option value="architecture_review">{t("Architecture review", "Mimari değerlendirme")}</option><option value="teacher_examples">{t("Prepare teacher examples", "Öğretmen örnekleri hazırlama")}</option><option value="sft_data">{t("SFT data preparation", "SFT veri hazırlığı")}</option><option value="lora_evaluation">{t("LoRA evaluation plan", "LoRA değerlendirme planı")}</option><option value="qlora_evaluation">{t("QLoRA evaluation plan", "QLoRA değerlendirme planı")}</option></select></label>
      <label>{t("Capability to improve", "Geliştirilecek yetenek")}<input required maxLength={600} value={objective} onChange={e => { setObjective(e.target.value); setDraft(null); }}/></label>
      <label>{t("Data manifest / snapshot reference", "Veri manifesti / snapshot referansı")}<input maxLength={256} value={dataset} onChange={e => { setDataset(e.target.value); setDraft(null); }} placeholder={t("Data reference whose permissions need review", "İzinleri incelenecek veri referansı")}/></label>
      <label>{t("Existing report reference", "Mevcut rapor referansı")}<select value={runId} onChange={e => { setRunId(e.target.value); setDraft(null); }}><option value="">{t("Optional · select a completed run", "İsteğe bağlı · tamamlanmış koşu seçin")}</option>{runs.map(run => <option key={run.run_id} value={run.run_id}>{run.run_id}</option>)}</select></label>
      <label>{t("Time limit (seconds)", "Süre üst sınırı (saniye)")}<input type="number" required min="1" max="14400" value={seconds} onChange={e => { setSeconds(Number(e.target.value)); setDraft(null); }}/></label>
      <label>{t("Model token limit", "Model token üst sınırı")}<input type="number" required min="1" max="350000" value={tokens} onChange={e => { setTokens(Number(e.target.value)); setDraft(null); }}/></label>
      <label>{t("RAM budget (GiB)", "RAM bütçesi (GiB)")}<input type="number" required min="1" max={ramMax} value={ram} onChange={e => { setRam(Number(e.target.value)); setDraft(null); }}/></label>
      <label>{t("VRAM budget (GiB)", "VRAM bütçesi (GiB)")}<input type="number" required min="1" max={vramMax} value={vram} onChange={e => { setVram(Number(e.target.value)); setDraft(null); }}/></label>
      <p className="agent-note agent-draft-full">{t("The draft contains references only. Data/model licensing, record cleaning, training eligibility and local model capacity have not been reviewed. Holdout data is excluded from training. A budget does not allocate resources; shared host admission is required separately.", "Taslak yalnız referansları içerir. Veri/model lisansı, kayıt temizliği, eğitim uygunluğu ve yerel model kapasitesi incelenmedi. Holdout verisi eğitimden dışlanır. Bütçe kaynak ayırmaz; paylaşımlı host kabulü ayrıca gerekir.")}</p>
      <p className="agent-note agent-draft-full">{t("Teacher call and training backends are not available yet. Selecting an external API is not approval; each actual request needs separate explicit approval. Do not enter API keys or secrets; the draft records approved=false and executed=false.", "Öğretmen çağrısı ve eğitim backend'i henüz yok. Dış API seçimi onay değildir; her gerçek istekten önce ayrı açık onay gerekir. API anahtarı veya sır girmeyin; taslak approved=false ve executed=false kaydeder.")}</p>
      {error && <p className="field-error agent-draft-full" role="alert">{error === 'required' ? t('Model reference, target and objective are required; training preparation also needs data or a verified report reference.', 'Model referansı, hedef ve amaç gerekli; eğitim hazırlığı için ayrıca veri veya doğrulanmış rapor referansı seçin.') : error === 'reference' ? t('Enter a model identity / profile reference in the teacher field, rather than a service address or access key.', 'Öğretmen alanına servis adresi veya erişim anahtarı yerine model kimliği / profil referansı girin.') : t('Budgets must be positive integers; proposed memory cannot exceed the known host total.', 'Bütçeler pozitif tam sayı olmalı; bellek önerisi bilinen host toplamını aşamaz.')}</p>}
      <div className="agent-actions agent-draft-full"><button className="button secondary" type="submit">{t("Download support / training preparation draft JSON", "Destek / eğitim hazırlık taslağı JSON indir")}</button>{trainingEvidence && <button className="button secondary" type="button" onClick={() => onEvidence(trainingEvidence)}>{t("Review training acceptance", "Eğitim kabulünü incele")}</button>}</div>
    </form>
    {draft && <div className="agent-draft-result" role="status"><strong>{t("Draft prepared; the teacher was not called and training was not run.", "Taslak hazırlandı; öğretmen çağrılmadı, eğitim çalıştırılmadı.")}</strong><p>{t("No GPU allocation, model call or new agent version was created.", "GPU ayırma, model çağrısı ve yeni eylemci sürümü oluşturma yapılmadı.")}</p><details><summary>{t("Inspect downloaded draft", "İndirilen taslağı incele")}</summary><pre>{draft}</pre></details></div>}
  </details>;
}
