import { t, locale } from './i18n';
import { useEffect, useRef, useState } from 'react';
import type { FieldIntent, PriorExperience } from './types';
import { ModeStreamForm } from './ModeStreamForm';
import { request } from './api';
import { requestId } from './requestId';
import { defaultParameters, ModeParameters, parameterError, scenarioName } from './ModeParameters';

type PublicSource = { source_id: string; dataset_id: string; task_id: string; source_version: string; license_id: string; usage_profile: 'noncommercial_research'; source_manifest_sha256: string };
type PublicProvenance = { dataset_id: string; split_id: string; session_id: string; source_manifest_sha256: string; source_revision: string; license_id: string; attribution: string; access_terms: string; usage_profile: 'noncommercial_research' };
type LocalAgentStudy = { schema: 'public-dev-local-agent-study.v1'; profile_set: 'smoke' | 'research'; max_experiments: number; max_wall_seconds: number; max_model_tokens: number };
type Snapshot = { local_agent_study?: LocalAgentStudy | null; source_kind: string; scoring_available: boolean; snapshot_sha256: string; sensors: string[]; rows: number; train_rows: number; evaluation_rows: number; readiness: string; first_utc: string | null; last_utc: string | null; time_axis?: string; source_time_kind?: string; fit_policy?: string; source_ranges?: { train: [number, number]; evaluation: [number, number] }; source?: PublicSource; provenance?: PublicProvenance; source_suite_manifest_sha256?: string; original_task_sha256?: string; profile_sha256?: string; semantics_sha256?: string; binding_sha256?: string };
const object = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value);
const hash = (value: unknown): value is string => typeof value === 'string' && /^[0-9a-f]{64}$/.test(value);
function validSnapshot(value: unknown, digest: string): value is Snapshot {
  if (!object(value) || value.snapshot_sha256 !== digest || !hash(value.snapshot_sha256)
    || typeof value.source_kind !== 'string' || !['synthetic', 'private_database', 'public_dev'].includes(value.source_kind)
    || typeof value.scoring_available !== 'boolean' || typeof value.readiness !== 'string'
    || !Array.isArray(value.sensors) || !value.sensors.length || value.sensors.length > 50
    || !value.sensors.every(sensor => typeof sensor === 'string' && sensor.length > 0)
    || new Set(value.sensors).size !== value.sensors.length
    || !['rows', 'train_rows', 'evaluation_rows'].every(key => typeof value[key] === 'number' && Number.isSafeInteger(value[key]) && (value[key] as number) > 0)
    || value.rows !== (value.train_rows as number) + (value.evaluation_rows as number)
    || !(value.first_utc === null || typeof value.first_utc === 'string') || !(value.last_utc === null || typeof value.last_utc === 'string')) return false;
  if (value.source_kind !== 'public_dev') return true;
  if (value.local_agent_study != null) {
    const policy = value.local_agent_study;
    if (!object(policy) || policy.schema !== 'public-dev-local-agent-study.v1'
      || typeof policy.profile_set !== 'string' || !['smoke', 'research'].includes(policy.profile_set)
      || !Object.entries({ max_experiments: 35, max_wall_seconds: 14400, max_model_tokens: 350000 }).every(([key, cap]) =>
        typeof policy[key] === 'number' && Number.isSafeInteger(policy[key]) && (policy[key] as number) >= 1 && (policy[key] as number) <= cap)) return false;
  }
  const source = value.source, provenance = value.provenance, ranges = value.source_ranges;
  if (!object(source) || !object(provenance) || !object(ranges)
    || !['source_id', 'dataset_id', 'task_id', 'source_version', 'license_id'].every(key => typeof source[key] === 'string' && source[key].length > 0)
    || !['dataset_id', 'split_id', 'session_id', 'source_revision', 'license_id', 'attribution', 'access_terms'].every(key => typeof provenance[key] === 'string' && provenance[key].length > 0)
    || source.usage_profile !== 'noncommercial_research' || provenance.usage_profile !== source.usage_profile
    || provenance.dataset_id !== source.dataset_id || provenance.source_revision !== source.source_version
    || provenance.license_id !== source.license_id || !hash(source.source_manifest_sha256)
    || provenance.source_manifest_sha256 !== source.source_manifest_sha256
    || !['source_suite_manifest_sha256', 'original_task_sha256', 'profile_sha256', 'semantics_sha256', 'binding_sha256'].every(key => hash(value[key]))
    || value.first_utc !== null || value.last_utc !== null || value.time_axis !== 'source_order_index' || value.source_time_kind !== 'naive'
    || value.fit_policy !== 'label_blind_source_order;normal_fit_not_guaranteed' || value.scoring_available !== true
    || !['ready', 'pending_scorer_installation'].includes(value.readiness) || (value.rows as number) > 4096
    || !['train', 'evaluation'].every(key => Array.isArray(ranges[key]) && ranges[key].length === 2
      && ranges[key].every(index => typeof index === 'number' && Number.isSafeInteger(index) && index >= 0))) return false;
  const train = ranges.train as number[], evaluation = ranges.evaluation as number[];
  return train[1] - train[0] === value.train_rows && evaluation[1] - evaluation[0] === value.evaluation_rows && train[1] <= evaluation[0];
}
type Statistic = { value: number | null; reason: string | null };
type Sensor = { name: string; valid: number; missing: number; nonfinite: number; statistics: Record<string, Statistic>; histogram_counts: number[]; histogram_edges: number[]; autocorrelation: Record<string, Statistic>; longest_constant_run: number };
type Summary = { rows: number; sensors: Sensor[]; pairs: { first: string; second: string; pearson: Statistic; spearman: Statistic; valid_pairs: number }[]; timeline: { regular: boolean; gap_count: number; reason: string | null }; notes: string[] };
const scenarios = ['healthy_single', 'healthy_multiple', 'healthy_load', 'step', 'drift', 'variance', 'correlation_break', 'oscillation_lag', 'unseen_mode', 'sensor_quality'];
const post = (body: unknown): RequestInit => ({ method: 'POST', body: JSON.stringify(body) });
const number = (stat?: Statistic) => stat?.value == null ? '—' : stat.value.toLocaleString(locale(), { maximumFractionDigits: 4 });

function statisticName(key: string): string {
const names: Record<string, string> = {
  minimum: 'Minimum', maximum: t("Maximum", "Maksimum"), mean: t("Mean", "Ortalama"), median: t("Median", "Medyan"),
  mad: t("Median absolute deviation (MAD)", "Medyan mutlak sapma (MAD)"), iqr: t("Interquartile range (IQR)", "Çeyrekler arası açıklık (IQR)"),
  p01: 'P01', p05: 'P05', p25: 'P25', p75: 'P75', p95: 'P95', p99: 'P99',
  tukey_outlier_count: t("Tukey outlier count", "Tukey aykırı değer sayısı"), std: t("Standard deviation", "Standart sapma"), variance: t("Variance", "Varyans"),
  skewness: t("Skewness", "Çarpıklık"), excess_kurtosis: t("Excess kurtosis", "Fazlalık basıklığı"), trend_per_second: t("Linear trend / second", "Doğrusal trend / saniye"),
};
return names[key] ?? key;
}
function StatisticsDetails({ summary }: { summary: Summary }) {
  const [selected, setSelected] = useState('');
  const sensor = summary.sensors.find(item => item.name === selected) ?? summary.sensors[0];
  return <details><summary>{t("Detailed statistics and autocorrelation", "Ayrıntılı istatistik ve otokorelasyon")}</summary>
    <label>{t("Sensor to analyze", "Analiz sensörü")}<select value={sensor?.name ?? ''} onChange={e => setSelected(e.target.value)}>{summary.sensors.map(item => <option key={item.name}>{item.name}</option>)}</select></label>
    {sensor && <><p>{t("Missing: ", "Eksik: ")}{sensor.missing}{t(" · nonfinite: ", " · sonlu olmayan: ")}{sensor.nonfinite}{t(" · longest constant run: ", " · en uzun sabit dizi: ")}{sensor.longest_constant_run}{t(" samples", " örnek")}</p>
      <p>{t("Variance and standard deviation use the sample definition (n−1). Outliers are retained; these markers are not process failure labels.", "Varyans ve standart sapma örneklem içindir (n−1). Aykırı değerler silinmez; bu işaretler süreç arızası etiketi değildir.")}</p>
      <table><thead><tr><th>{t("Statistic", "Özellik")}</th><th>{t("Value", "Değer")}</th><th>{t("Reason unavailable", "Hesaplanamama nedeni")}</th></tr></thead><tbody>{Object.entries(sensor.statistics).map(([key, stat]) => <tr key={key}><td>{statisticName(key)}</td><td>{number(stat)}</td><td>{stat.reason ?? '—'}</td></tr>)}</tbody></table>
      <h3>{t("Autocorrelation (ACF)", "Otokorelasyon (ACF)")}</h3><p>{t("Lag is measured in samples. ACF is unavailable for an irregular time axis.", "Gecikme örnek sayısıdır. Düzensiz zaman ekseninde ACF hesaplanmaz.")}</p>
      <table><thead><tr><th>{t("Lag", "Gecikme")}</th><th>{t("Autocorrelation", "Otokorelasyon")}</th><th>{t("Reason unavailable", "Hesaplanamama nedeni")}</th></tr></thead><tbody>{Object.entries(sensor.autocorrelation).map(([lag, stat]) => <tr key={lag}><td>{lag}</td><td>{number(stat)}</td><td>{stat.reason ?? '—'}</td></tr>)}</tbody></table>
    </>}
  </details>;
}

export function OperatingModesPage({ connected, modelRunsEnabled = false, experimentKind, onExperimentKindChange, priorExperience, onClearPrior, fieldIntent, onClearFieldIntent, onEditFieldIntent, onStarted }: { connected: boolean; modelRunsEnabled?: boolean; experimentKind: 'grid' | 'agent'; onExperimentKindChange: (kind: 'grid' | 'agent') => void; priorExperience: PriorExperience | null; onClearPrior: () => void; fieldIntent: FieldIntent | null; onClearFieldIntent: () => void; onEditFieldIntent: () => void; onStarted: () => void }) {
  const pending = useRef<{ serialized: string; key: string } | null>(null);
  async function startExperiment(path: string, body: Record<string, unknown>) {
    const serialized = JSON.stringify({ path, body });
    if (pending.current?.serialized !== serialized) pending.current = { serialized, key: requestId() };
    await request(path, post({ ...body, idempotency_key: pending.current.key }));
    pending.current = null;
    onStarted();
  }
  const fieldBody = fieldIntent ? { field_intent: fieldIntent } : {};
  const historyBody = priorExperience && connected ? { prior_experience: priorExperience } : {};
  const [snapshotDigest, setSnapshotDigest] = useState('');
  const [sources, setSources] = useState<{ source_id: string; sensors: string[]; row_limit: number; entity_required: boolean; source_kind?: string }[]>([]);
  const [sourceId, setSourceId] = useState('');
  const [features, setFeatures] = useState<string[]>([]);
  const [rowLimit, setRowLimit] = useState(512);
  const [trainRows, setTrainRows] = useState(192);
  const [sourceError, setSourceError] = useState<string | null>(null);
  const [start, setStart] = useState('');
  const [end, setEnd] = useState('');
  const [entity, setEntity] = useState('');
  useEffect(() => { if (connected) request<{ items: typeof sources }>('/mode-sources').then(result => setSources(result.items.filter(item => !item.source_kind || item.source_kind === 'private_database'))).catch(cause => setSourceError(String(cause))); }, [connected]);
  const [scenario, setScenario] = useState('healthy_multiple');
  const [seed, setSeed] = useState(0);
  const [snapshot, setSnapshot] = useState<Snapshot | null>(null);
  const publicDev = snapshot?.source_kind === 'public_dev';
  const agentPolicy = publicDev ? snapshot.local_agent_study : null;
  const publicAgentDenied = publicDev && !agentPolicy;
  const [summary, setSummary] = useState<Summary | null>(null);
  const [partition, setPartition] = useState('train');
  const [methods, setMethods] = useState(['lsh', 'optics', 'som']);
  const [k, setK] = useState(3);
  const [parameters, setParameters] = useState(defaultParameters);
  const configurationError = parameterError(parameters);
  const [wall, setWall] = useState(600);
  const [proposals, setProposals] = useState(6);
  const [agentWall, setAgentWall] = useState(7200);
  const [tokens, setTokens] = useState(180000);
  const [profileSet, setProfileSet] = useState<'smoke' | 'research'>('research');
  const boundedInteger = (value: number, maximum: number) => Number.isInteger(value) && value >= 1 && value <= maximum;
  const proposalCap = agentPolicy?.max_experiments ?? 35;
  const wallCap = agentPolicy?.max_wall_seconds ?? 14400;
  const tokenCap = agentPolicy?.max_model_tokens ?? 350000;
  const agentBudgetValid = boundedInteger(proposals, proposalCap) && boundedInteger(agentWall, wallCap) && boundedInteger(tokens, tokenCap)
    && (!agentPolicy || profileSet === agentPolicy.profile_set);
  useEffect(() => {
    if (!agentPolicy) return;
    setProposals(value => Math.min(value, agentPolicy.max_experiments));
    setAgentWall(value => Math.min(value, agentPolicy.max_wall_seconds));
    setTokens(value => Math.min(value, agentPolicy.max_model_tokens));
    setProfileSet(agentPolicy.profile_set);
  }, [agentPolicy]);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  async function action(work: () => Promise<void>) { setBusy(true); setError(null); try { await work(); } catch (cause) { setError(cause instanceof Error ? cause.message : t("Operation failed", "İşlem başarısız")); } finally { setBusy(false); } }
  async function statistics(item: Snapshot, part: string) { setSummary(await request<Summary>(`/mode-snapshots/${item.snapshot_sha256}/statistics?partition=${part}`)); }
  function download() { const url = URL.createObjectURL(new Blob([JSON.stringify({ snapshot, partition, summary }, null, 2)], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = `mode-statistics-${snapshot?.snapshot_sha256.slice(0, 12)}.json`; link.click(); URL.revokeObjectURL(url); }
  return <div className="page-grid">
    <section className="panel" aria-labelledby="mode-field-intent-title"><h2 id="mode-field-intent-title">{t("Field research intent", "Saha araştırma amacı")}</h2>{fieldIntent ? <><dl><dt>{t("Asset label · user supplied", "Varlık etiketi · kullanıcı beyanı")}</dt><dd>{fieldIntent.asset_id}</dd><dt>{t("Research intent", "Araştırma amacı")}</dt><dd>{fieldIntent.goal_kind === 'digital_twin' ? t("Digital twin research", "Dijital ikiz araştırması") : t("Predictive maintenance research", "Kestirimci bakım araştırması")}</dd><dt>{t("Study objective", "Çalışma hedefi")}</dt><dd>{fieldIntent.objective}</dd></dl><p>{t("This intent is added as advisory context to a new parameter comparison or agent study using the selected snapshot. It does not establish an authorized source/asset mapping or maintenance action; method, score and budget stay unchanged. It is not added to the OMR diagnostic stream below.", "Seçilen snapshot ile yeni parametre karşılaştırmasına veya agent araştırmasına danışma bilgisi olarak eklenir. Yetkili kaynak/varlık eşlemesi ve bakım aksiyonu değildir; yöntem, skor ve bütçe değişmez. Aşağıdaki OMR tanı akışına eklenmez.")}</p></> : <p>{t("No field intent has been added. You can continue the experiment by selecting data and a method.", "Saha amacı eklenmedi. Veri ve yöntem seçimiyle mevcut deney akışına devam edebilirsiniz.")}</p>}<div className="agent-actions"><button className="button secondary small" onClick={onEditFieldIntent} disabled={busy}>{fieldIntent ? t("Edit field intent", "Saha amacını düzenle") : t("Add field intent", "Saha amacı ekle")}</button>{fieldIntent && <button className="button secondary small" onClick={onClearFieldIntent} disabled={busy}>{t("Remove field intent", "Saha amacını kaldır")}</button>}</div></section>
    {priorExperience && <section className="panel experience-handoff" aria-label={t("Selected previous findings", "Seçili geçmiş bulgular")}><h2>{t("Selected previous findings", "Seçili geçmiş bulgular")}</h2><p>{priorExperience.records.length}{t(" verified development records · source run ", " doğrulanmış geliştirme kaydı · kaynak koşu ")}<code>{priorExperience.source_run_id}</code></p><p>{t("Added only as advisory context to a new parameter comparison or agent study. Previous scores do not replace new measurements; the deterministic parameter plan stays unchanged. Not added to the OMR diagnostic stream below.", "Yalnız yeni parametre karşılaştırması veya agent araştırmasına danışma bağlamı olarak eklenir. Geçmiş skorlar yeni ölçümün yerine geçmez; deterministik parametre planı değişmez. Aşağıdaki OMR tanı akışına eklenmez.")}</p><button className="button secondary small" onClick={onClearPrior} disabled={busy}>{t("Remove previous findings", "Geçmiş bulguları kaldır")}</button></section>}
    <section className="panel"><div className="panel-heading"><div><h2>{t("Operating modes and OMR", "Çalışma modları ve OMR")}</h2><p>{t("Immutable data → learned modes → nearest neighbors → measured comparison", "Değişmez veri → eğitim modları → en yakın komşular → ölçülen karşılaştırma")}</p></div></div>
      <p>{publicDev ? t("The installed public DEV snapshot contains real source data. Local model research requires a separate source and user grant; a manual CPU comparison does not grant model authority. The OMR diagnostic stream is disabled for this data path.", "Kurulu public DEV snapshot gerçek kaynak verisidir. Yerel model araştırması ayrı, kaynak ve kullanıcıya bağlı izin gerektirir; manuel CPU karşılaştırması model yetkisi vermez. OMR tanı akışı bu veri yolunda kapalıdır.") : snapshot?.source_kind === 'private_database' ? t("The selected PostgreSQL data is analyzed as an immutable snapshot.", "Seçilen PostgreSQL verisi değişmez bir snapshot olarak analiz edilir.") : t("Synthetic scenarios are reproducible test data; they do not establish acceptance on real industrial data.", "Sentetik senaryolar tekrar üretilebilir test verisidir; gerçek endüstriyel veri kabulü değildir.")}{t(" A parameter grid makes no model calls. Agent research uses a local model to propose a limited number of configurations; candidates are measured through the Director and Scorer workflow.", " Parametre taraması model çağrısı yapmaz. Agent araştırması yerel modelle sınırlı sayıda yapılandırma önerir; adaylar Director ve Scorer akışında ölçülür.")}</p>
      {!connected && <p role="status">{t("The Lab API is disconnected. Data generation and experiment launch are unavailable.", "Lab API bağlı değil. Veri üretimi ve deney başlatma kullanılamıyor.")}</p>}
      <h3>{t("Configured PostgreSQL source", "Yapılandırılmış PostgreSQL kaynağı")}</h3><p>{t("Connection details stay on the server. Only authorized views and sensors can be selected.", "Bağlantı bilgileri sunucuda kalır. Yalnız izin verilen görünüm ve sensörler seçilebilir.")}</p>
      {sources.length ? <div className="run-form"><label>{t("Source", "Kaynak")}<select value={sourceId} onChange={e => { setSourceId(e.target.value); const source = sources.find(item => item.source_id === e.target.value); setFeatures(source?.sensors ?? []); const limit = Math.min(512, source?.row_limit ?? 512); setRowLimit(limit); setTrainRows(Math.min(192, Math.floor(limit / 2))); }}><option value="">{t("Select a source", "Kaynak seçin")}</option>{sources.map(source => <option key={source.source_id}>{source.source_id}</option>)}</select></label><fieldset><legend>{t("Features (", "Özellikler (")}{features.length}/50)</legend>{sources.find(source => source.source_id === sourceId)?.sensors.map(sensor => <label key={sensor}><input type="checkbox" checked={features.includes(sensor)} onChange={e => setFeatures(values => e.target.checked ? [...values, sensor] : values.filter(value => value !== sensor))}/>{sensor}</label>)}</fieldset><label>{t("Row limit", "Satır sınırı")}<input type="number" min="32" max={sources.find(source => source.source_id === sourceId)?.row_limit ?? 4096} value={rowLimit} onChange={e => setRowLimit(Number(e.target.value))}/></label><label>{t("Training rows", "Eğitim satırları")}<input type="number" min="16" max={rowLimit - 1} value={trainRows} onChange={e => setTrainRows(Number(e.target.value))}/></label><label>{t("Start (UTC ISO)", "Başlangıç (UTC ISO)")}<input value={start} placeholder="2026-01-01T00:00:00Z" onChange={e => setStart(e.target.value)}/></label><label>{t("End (UTC ISO)", "Bitiş (UTC ISO)")}<input value={end} placeholder="2026-01-02T00:00:00Z" onChange={e => setEnd(e.target.value)}/></label><label>{t("Asset", "Varlık")}<input value={entity} onChange={e => setEntity(e.target.value)}/></label><button className="button secondary" disabled={busy || !sourceId || !start || !end || !features.length || trainRows >= rowLimit} onClick={() => void action(async () => { const source = sources.find(item => item.source_id === sourceId)!; const item = await request<Snapshot>('/mode-snapshots/database', post({ source_id: sourceId, sensors: features, start_utc: start, end_utc: end, entity: source.entity_required ? entity : null, row_limit: Math.min(rowLimit, source.row_limit), train_rows: trainRows })); setSnapshot(item); await statistics(item, partition); })}>{t("Capture source snapshot", "Kaynak snapshot al")}</button></div> : <p>{sourceError ?? t("No authorized data source has been configured yet.", "İzin verilen veri kaynağı henüz yapılandırılmadı.")}</p>}
      <h3>{t("Installed data source", "Kurulu veri kaynağı")}</h3><p>{t("Open an immutable record with the snapshot SHA-256 supplied by the operator. This does not import data or install Scorer.", "Operatörün verdiği snapshot SHA-256 ile değişmez kaydı açın. Bu işlem veri içe aktarması veya Scorer kurulumu yapmaz.")}</p>
      <div className="run-form"><label>Snapshot SHA-256<input value={snapshotDigest} disabled={busy} spellCheck={false} maxLength={64} onChange={event => setSnapshotDigest(event.target.value)} placeholder={t("64-character SHA-256", "64 karakterlik SHA-256")}/></label><button className="button secondary" disabled={busy || !connected || !/^[0-9a-f]{64}$/.test(snapshotDigest.trim())} onClick={() => void action(async () => {
        const digest = snapshotDigest.trim();
        const item = await request<unknown>(`/mode-snapshots/${digest}`);
        if (!validSnapshot(item, digest)) throw new Error(t("The snapshot identity, source provenance or time information could not be verified.", "Snapshot yanıtının kimliği, kaynak kökeni veya zaman bilgisi doğrulanamadı."));
        if (item.source_kind === 'public_dev') { setMethods(values => values.slice(0, 2)); setWall(value => Math.min(value, 600)); }
        setSnapshot(item); setSummary(null); await statistics(item, partition);
      })}>{t("Open installed data source", "Kurulu veri kaynağını aç")}</button></div>
      <h3>{t("Synthetic source", "Sentetik kaynak")}</h3>
      <div className="run-form"><label>{t("Scenario", "Senaryo")}<select value={scenario} onChange={e => setScenario(e.target.value)}>{scenarios.map(value => <option key={value} value={value}>{scenarioName(value)}</option>)}</select></label><label>{t("Source seed", "Kaynak seed")}<input type="number" min="0" max="4294967295" value={seed} onChange={e => setSeed(Number(e.target.value))}/></label>
        <button className="button primary" disabled={busy || !connected} onClick={() => void action(async () => { const item = await request<Snapshot>('/mode-snapshots', post({ scenario, seed, train_rows: 192, evaluation_rows: 96 })); setSnapshot(item); await statistics(item, partition); })}>{t("Generate synthetic snapshot", "Sentetik snapshot üret")}</button></div>
      {error && <p className="field-error" role="alert">{error}</p>}
      {snapshot && publicDev && snapshot.source && snapshot.provenance && <div className="experience-handoff"><h3>{t("Real public DEV source · ", "Gerçek public DEV kaynağı · ")}{snapshot.source.dataset_id}</h3><dl><dt>{t("Source / development task", "Kaynak / geliştirme görevi")}</dt><dd>{snapshot.source.source_id} · {snapshot.source.task_id}</dd><dt>{t("License / use", "Lisans / kullanım")}</dt><dd>{snapshot.source.license_id}{t(" · Noncommercial research", " · Ticari olmayan araştırma")}</dd><dt>{t("Original source revision", "Özgün kaynak sürümü")}</dt><dd>{snapshot.source.source_version}</dd><dt>{t("Attribution", "Atıf")}</dt><dd>{snapshot.provenance.attribution}</dd><dt>{t("Access terms", "Erişim koşulları")}</dt><dd>{snapshot.provenance.access_terms}</dd></dl><details><summary>{t("Original source and derived binding references", "Özgün kaynak ve türetilmiş bağlama referansları")}</summary><dl><dt>{t("Original split / session", "Özgün split / oturum")}</dt><dd>{snapshot.provenance.split_id} · {snapshot.provenance.session_id}</dd><dt>{t("Source manifest SHA-256", "Kaynak manifest SHA-256")}</dt><dd>{snapshot.source.source_manifest_sha256}</dd><dt>{t("Source suite manifest SHA-256", "Kaynak suite manifest SHA-256")}</dt><dd>{snapshot.source_suite_manifest_sha256}</dd><dt>{t("Original task SHA-256", "Özgün görev SHA-256")}</dt><dd>{snapshot.original_task_sha256}</dd><dt>{t("Profile SHA-256", "Profil SHA-256")}</dt><dd>{snapshot.profile_sha256}</dd><dt>{t("Semantics SHA-256", "Semantik SHA-256")}</dt><dd>{snapshot.semantics_sha256}</dd><dt>{t("Derived binding SHA-256", "Türetilmiş bağlama SHA-256")}</dt><dd>{snapshot.binding_sha256}</dd></dl></details><p>{t("This license/provenance record does not grant training or export permission. A public DEV comparison is not independent holdout acceptance.", "Bu kaynak lisans/köken kaydı eğitim veya dışa aktarma izni yerine geçmez. Public DEV karşılaştırması bağımsız holdout kabulü değildir.")}</p></div>}
      {snapshot && <><p><code>{snapshot.snapshot_sha256}</code></p><p>{snapshot.rows}{t(" rows · ", " satır · ")}{snapshot.sensors.length}{t(" sensors · ", " sensör · ")}{publicDev ? t("fit / source-order reference", "fit / kaynak sırası referansı") : t("training", "eğitim")} {snapshot.train_rows}{t(" / evaluation ", " / değerlendirme ")}{snapshot.evaluation_rows}</p>{publicDev ? <><p>{t("Time axis: source row order. Source times have no timezone (naive); no UTC times are invented.", "Zaman ekseni: kaynak satır sırası. Kaynak zamanları saat dilimi içermeyen değerlerdir (naive); UTC zamanı üretilmez.")}</p><p>{t("The fit slice follows source order; normal operation is not guaranteed. Labels do not guide the fit selection.", "Fit dilimi kaynak sırasına göre seçilir; garantili normal işletim dilimi değildir. Etiketler fit seçimini yönlendirmez.")}</p>{snapshot.source_ranges && <p>{t("Source row ranges (start inclusive, end exclusive): fit [", "Kaynak satır aralıkları (başlangıç dahil, bitiş hariç): fit [")}{snapshot.source_ranges.train.join(', ')}{t("), evaluation [", "), değerlendirme [")}{snapshot.source_ranges.evaluation.join(', ')}).</p>}</> : <p>{snapshot.first_utc} — {snapshot.last_utc}</p>}<p>{t("Installation: ", "Kurulum: ")}{snapshot.readiness === 'ready' ? t("Scorer ready", "Scorer hazır") : t("Awaiting Scorer installation", "Scorer kurulumu bekleniyor")}. {publicDev ? t("The original source split and embargo are preserved; no additional rows are removed.", "Özgün kaynak split ve embargo korunur; ek satır çıkarılmaz.") : t("The training-derived embargo is also removed from the start of evaluation.", "Eğitimden türetilen embargo, değerlendirme başlangıcından ayrıca çıkarılır.")}</p>
        {!publicDev && <button className="button secondary" disabled={busy || !snapshot.scoring_available || snapshot.readiness === 'ready'} onClick={() => void action(async () => setSnapshot(await request<Snapshot>(`/mode-snapshots/${snapshot.snapshot_sha256}/install`, post({}))))}>{t("Prepare for Scorer", "Scorer için hazırla")}</button>}{publicDev && snapshot.readiness !== 'ready' && <p>{t("The operator must complete Scorer installation; it cannot be installed from this view.", "Scorer kurulumu operatör tarafından tamamlanmalı; bu görünümden kurulmaz.")}</p>}{!snapshot.scoring_available && <p>{t("This source has no trusted evaluation labels. Descriptive analysis is available; Scorer measurement is unavailable.", "Bu veri kaynağında güvenilir değerlendirme etiketleri yok. Tanımlayıcı analiz hazır; Scorer ölçümü kullanılamıyor.")}</p>}
      </>}
    </section>
    {snapshot && <section className="panel"><div className="panel-heading"><h2>{t("Descriptive statistics", "Tanımlayıcı istatistik")}</h2><select aria-label={t("Data partition", "Veri dönemi")} value={partition} disabled={busy} onChange={e => { setPartition(e.target.value); void action(() => statistics(snapshot, e.target.value)); }}><option value="train">{publicDev ? t("Fit / source-order reference", "Fit / kaynak sırası referansı") : t("Training", "Eğitim")}</option><option value="evaluation">{t("Evaluation", "Değerlendirme")}</option><option value="all">{t("All", "Tümü")}</option></select><button className="button secondary" onClick={download} disabled={!summary}>{t("Download JSON", "JSON indir")}</button></div><p>{t("Evaluation statistics are for the user; they are not sent to the proposal provider. Missing values are not filled.", "Değerlendirme istatistikleri kullanıcı içindir; öneri sağlayıcısına aktarılmaz. Eksik değerler doldurulmaz.")}</p>
      {summary && <><p>{summary.rows}{t(" rows · ", " satır · ")}{publicDev ? t("Time regularity and gaps were not measured; source row order is used.", "Zaman düzeni ve boşluklar ölçülmedi; kaynak satır sırası.") : <>{t("time axis ", "zaman ekseni ")}{summary.timeline.regular ? t("regular", "düzenli") : t("irregular", "düzensiz")} · {summary.timeline.gap_count}{t(" gaps", " boşluk")}</>}</p><div style={{ overflowX: 'auto' }}><table><thead><tr><th>{t("Sensor", "Sensör")}</th><th>{t("Valid / missing", "Geçerli / eksik")}</th><th>{t("Mean", "Ortalama")}</th><th>Std</th><th>Min</th><th>{t("Median", "Medyan")}</th><th>Max</th><th>{t("Distribution", "Dağılım")}</th></tr></thead><tbody>{summary.sensors.map(sensor => <tr key={sensor.name}><td>{sensor.name}</td><td>{sensor.valid} / {sensor.missing + sensor.nonfinite}</td>{['mean', 'std', 'minimum', 'median', 'maximum'].map(key => <td key={key} title={sensor.statistics[key]?.reason ?? ''}>{number(sensor.statistics[key])}</td>)}<td><svg role="img" aria-label={`${sensor.name} histogram`} width="160" height="40" viewBox="0 0 160 40">{sensor.histogram_counts.map((count, index, counts) => <rect key={index} x={index * 160 / counts.length} y={40 - 38 * count / Math.max(...counts, 1)} width={150 / counts.length} height={38 * count / Math.max(...counts, 1)} fill="currentColor"><title>{count}{t(" samples · ", " örnek · ")}{sensor.histogram_edges[index]} — {sensor.histogram_edges[index + 1]}</title></rect>)}</svg></td></tr>)}</tbody></table></div><h3>{t("Sensor relationships", "Sensör ilişkileri")}</h3><table><thead><tr><th>{t("Pair", "Çift")}</th><th>Pearson</th><th>Spearman</th><th>{t("Valid pairs", "Geçerli çift")}</th></tr></thead><tbody>{summary.pairs.map(pair => <tr key={`${pair.first}:${pair.second}`}><td>{pair.first} / {pair.second}</td><td title={pair.pearson.reason ?? ''}>{number(pair.pearson)}</td><td title={pair.spearman.reason ?? ''}>{number(pair.spearman)}</td><td>{pair.valid_pairs}</td></tr>)}</tbody></table><StatisticsDetails summary={summary}/>{summary.notes.map(note => <p key={note}>{note}</p>)}</>}
    </section>}
    {snapshot && <section className="panel"><h2>{t("Operating mode experiment", "Çalışma modu deneyi")}</h2>
      <label>{t("Experiment type", "Deney türü")}<select value={experimentKind} disabled={busy} onChange={e => onExperimentKindChange(e.target.value as 'grid' | 'agent')}><option value="agent">{t("Local experiment agent", "Yerel deney eylemcisi")}</option><option value="grid">{t("Manual parameter comparison (0 model tokens)", "Manuel parametre karşılaştırması (0 model tokenı)")}</option></select></label>
      <p>{t("Mode tolerance → nearest neighbor estimate of normal values → continuous sensor residuals and OMR. Mode distance, SOM distance and OMR are separate measurements. Success is not shown before results are measured.", "Mod toleransı → en yakın komşu normal değer tahmini → sürekli sensör residual'ları ve OMR. Mod uzaklığı, SOM uzaklığı ve OMR ayrı ölçümlerdir. Sonuçlar ölçülmeden başarı gösterilmez.")}</p>
      {experimentKind === 'grid' ? <>{publicDev && <p>{t("Public DEV limit: at most 2 candidates, 600 seconds and 0 model tokens. Fit/development measurements are not evidence of holdout or general success.", "Public DEV sınırı: en fazla 2 aday, 600 saniye, 0 model tokenı. Fit/geliştirme ölçümü holdout veya genel başarı kanıtı değildir.")}</p>}<p>{t("Each selected method is one candidate. Seed repeats, baselines, time limits, cancellation and reports are managed by the existing experiment workflow.", "Seçilen her yöntem bir adaydır. Seed tekrarları, baseline, süre sınırı, iptal ve rapor mevcut deney akışı tarafından yönetilir.")}</p><div className="run-form">{['lsh', 'optics', 'som'].map(method => <label key={method}><input type="checkbox" disabled={publicDev && !methods.includes(method) && methods.length >= 2} checked={methods.includes(method)} onChange={e => setMethods(values => e.target.checked ? [...values, method] : values.filter(value => value !== method))}/>{method.toUpperCase()}</label>)}<label>{t("Neighbor count k", "Komşu sayısı k")}<input type="number" min="1" max="128" value={k} onChange={e => setK(Number(e.target.value))}/></label><label>{t("Time budget (seconds)", "Süre bütçesi (saniye)")}<input type="number" min="1" max={publicDev ? 600 : 14400} value={wall} onChange={e => setWall(Number(e.target.value))}/></label><ModeParameters methods={methods} values={parameters} onChange={setParameters}/>{configurationError && <p role="alert" className="field-error">{configurationError}</p>}<button className="button primary" disabled={busy || !connected || !methods.length || (publicDev && methods.length > 2) || !!configurationError || !boundedInteger(k, 128) || !boundedInteger(wall, publicDev ? 600 : 14400) || snapshot.readiness !== 'ready'} onClick={() => void action(async () => { await startExperiment('/mode-experiments', { snapshot_sha256: snapshot.snapshot_sha256, configurations: methods.map(method => ({ ...parameters, method, k, seed })), wall_seconds: wall, ...historyBody, ...fieldBody }); })}>{t("Start measurement with 0 tokens", "0 token ile ölçümü başlat")}</button></div></> : <>
        <p>{t("The main local model designs the experiment by selecting proposals among server-validated LSH, OPTICS and SOM configurations. The backend executes the candidate; independent Scorer results inform the next local proposal within the same run. The search includes neighbor count and weighting, distance metric, mode tolerance, calibration, alarms and method hyperparameters. Proposals are validated as configurations; the model is not asked to write code. Verified DEV summaries inform the next proposal; hidden labels, raw sensor series and holdout data are not provided to the model.", "Ana yerel model deneyi tasarlar: sunucunun doğruladığı LSH, OPTICS ve SOM yapılandırmaları arasından öneri seçer. Backend adayı yürütür; bağımsız Scorer sonuçları aynı koşuda sonraki yerel öneriye geri bildirim olur. Komşu sayısı ve ağırlığı, uzaklık metriği, mod toleransı, kalibrasyon, alarm ve yöntem hiperparametreleri bu aramanın parçasıdır. Öneri yapılandırma olarak doğrulanır; modelden kod istenmez. Doğrulanmış DEV sonuç özetleri sonraki öneriye geri bildirim olur; gizli etiketler, ham sensör serisi ve holdout modele verilmez.")}</p>
        <p>{t("Time and token budgets bound the entire study; model calls remain subject to the existing resource admission and GPU queue rules.", "Süre ve token bütçeleri bütün araştırmayı sınırlar; model çağrıları mevcut kaynak kabulü ve GPU sıra kurallarına tabidir.")}</p>
        {publicAgentDenied && <p role="status">{t("No local experiment agent grant is registered for this public DEV data. You can explicitly select a manual comparison with 0 tokens; the experiment type is not changed automatically.", "Bu public DEV verisi için yerel deney eylemcisi izni kayıtlı değil. Manuel 0 token karşılaştırmasını açıkça seçebilirsiniz; deney türü otomatik değiştirilmez.")}</p>}{!modelRunsEnabled && <p role="status">{t("Local model calls are disabled in this profile. The local agent cannot start; a manual comparison with 0 tokens is a separate option. Model authorization and resource admission must be provided on the server.", "Bu profilde yerel model çağrıları kapalı. Yerel eylemci başlatılamaz; manuel 0 token karşılaştırması ayrı bir seçenektir. Model çalıştırma izni ve kaynak kabulü sunucuda sağlanmalıdır.")}</p>}
        {agentPolicy && <p role="status">{t("Registered local research limit: ", "Kayıtlı yerel araştırma sınırı: ")}{proposalCap}{t(" proposals · ", " öneri · ")}{wallCap}{t(" seconds · ", " saniye · ")}{tokenCap}{t(" tokens · ", " token · ")}{agentPolicy.profile_set}{t(" profile. This data grant alone does not start a model or GPU.", " profili. Bu veri izni tek başına model veya GPU başlatmaz.")}</p>}
        <div className="run-form"><label>{t("Proposal count", "Öneri sayısı")}<input type="number" min="1" max={proposalCap} value={proposals} onChange={e => setProposals(Number(e.target.value))}/></label><label>{t("Total time budget (seconds)", "Toplam süre bütçesi (saniye)")}<input type="number" min="1" max={wallCap} value={agentWall} onChange={e => setAgentWall(Number(e.target.value))}/></label><label>{t("Total model token budget", "Toplam model token bütçesi")}<input type="number" min="1" max={tokenCap} value={tokens} onChange={e => setTokens(Number(e.target.value))}/></label><label>{t("Experiment profile", "Deney profili")}<select disabled={!!agentPolicy} value={profileSet} onChange={e => setProfileSet(e.target.value as 'smoke' | 'research')}><option value="research">{t("Research", "Araştırma")}</option><option value="smoke">{t("Small validation", "Küçük doğrulama")}</option></select></label>
          {!agentBudgetValid && <p role="alert" className="field-error">{t("Proposals 1–", "Öneri 1–")}{proposalCap}{t(", time 1–", ", süre 1–")}{wallCap}{t(" seconds and tokens 1–", " saniye ve token 1–")}{tokenCap}{t(" must be integers within these ranges; the profile must match the registered grant.", " aralığında tam sayı olmalı; profil kayıtlı izinle eşleşmelidir.")}</p>}
          <button className="button primary" disabled={busy || !connected || publicAgentDenied || !modelRunsEnabled || !agentBudgetValid || snapshot.readiness !== 'ready'} onClick={() => void action(async () => { if (publicAgentDenied) throw new Error(t("No local model research grant is available for this public DEV source.", "Public DEV kaynağında yerel model araştırması izni yok.")); if (!modelRunsEnabled) throw new Error(t("Local model research is disabled.", "Yerel model araştırmaları kapalı.")); await startExperiment('/mode-agent-experiments', { snapshot_sha256: snapshot.snapshot_sha256, experiments: proposals, wall_seconds: agentWall, model_tokens: tokens, profile_set: profileSet, ...historyBody, ...fieldBody }); })}>{t("Start research with the local model", "Yerel modelle araştırmayı başlat")}</button>
        </div><p>{t("Monitor or stop the run and open its report from Experiments. A launch response is not evidence of research success.", "Koşu Deneyler ekranından izlenir, durdurulur ve raporu açılır. Başlatma yanıtı araştırma başarısı kanıtı değildir.")}</p>
      </>}
    </section>}
    {!publicDev && <details className="panel"><summary>{t("Secondary CPU OMR diagnostic stream · no model proposals or improvement score", "İkincil CPU OMR tanı akışı · model önerisi ve gelişim puanı yok")}</summary><ModeStreamForm connected={connected} onStarted={onStarted}/></details>}
  </div>;
}
